spring:
  application:
    name: demo05-prefetch
  rabbitmq:
    addresses: 127.0.0.1
    host: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
