spring:
  application:
    name: demo4-amqp-reliability-delivery
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: CORRELATED    # \u4EA4\u6362\u673A\u7684\u786E\u8BA4
    publisher-returns: true               # \u961F\u5217\u7684\u786E\u8BA4
    listener:
      simple:
        acknowledge-mode: manual          # 把消息确认模式改为手动确认
        prefetch: 1                       # 每次从队列中取回消息的数量

logging:
  level:
    org.springframework.amqp: debug
